### PR TITLE
Refactor/demo page

### PR DESCRIPTION
**Pull request by mverissimo**
# Description

The `demo page` was redesigned and with this, all `demos` were migrated to typescript, and I did some design changes on some `demos`.

 _Please read the changes with attention :)_

## Changes

- File System API
  Migrated to typescript
  New design

- FullScreen API
  Migrated to typescript

- Clipboard API
  Migrated to typescript
  New design

- Broadcast
  Migrated to typescript
  New design

- Network Info
  Migrated to typescript
  New design

- Resize Observer
  Migrated to typescript
  New design

- Web payment API
  New design
  **I need help with this to migrate to typescript**

- Vibration API
  Migrated to typescript
  New design

- Battery API
  Migrated to typescript
  New design

- Drag and Drop
  Migrated to typescript
  New design

- Image Capture
  Migrated to typescript
  New design

- Web Share API
  Migrated to typescript

- Geolocation API
  Migrated to typescript
  New design

- Picture in Picture
  Migrated to typescript

- Screen Capture
  Migrated to typescript
  New design

- Web Speech API
  Migrated to typescript
  New design

- CSS Font Loading API
  Migrated to typescript
  New design

- Next
The [pages](https://nextjs.org/docs/api-reference/next.config.js/custom-page-extensions) need be created with a new extension, to ability create other folders inside them.

- Core
  The `hasSupport` func has been standardized on all files I think this is good to keep a pattern.
  eg: `Boolean('clipboard' in navigator)`

Some packages were added to support some typescript types.

Fixes #134 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [x] My code follows the [style guidelines](https://github.com/atapas/webapis-playground/blob/master/HOW-TO-ADD-DEMO.md) of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by mverissimo** [comment]
> > Hello @atapas can you check the new `demo page` design before _code review,_ please! Only the `fullscreen` was fully updated.
> 
> Hey @mverissimo, I had a look at it from my phone now. I loved the way you have categorized support, API and code.
> 
> A small feedback of those button alignment. Could be only in mobile now it is in 2 rows. Also the image and button to go full screen need some space between.
> 
> The current design has all the required content. I'm happy with it. Some aesthetics to take care.
> 
> P.S. I m on vacation so do not have laptop to see it yet. May be @max-programming and @niteshseram can help getting this PR moving forward from the review perspective. However, I want to do a final review before the merge.
> 
> Thanks for making it better.

Thanks, the buttons were adjusted to auto-size based on device width, I think this was finished, only waiting for `design review` to start migration for the other demos.

PSC @niteshseram @max-programming

**Review by niteshseram — COMMENTED** [review]
@mverissimo This looks great. Just a suggestion. In the Live preview section, don't align the preview to the center, make it align from the left. Like in the full-screen preview demo, the preview is aligned centered. That doesn't look good there is so much wide space on the left. And also name the button as `Go Fullscreen`
Capture
.

**Comment by mverissimo** [comment]
@niteshseram adjusted!

I have some questions, to prevent too many files on `code review`  I think is better to migrate 2 or 3 demos by PR, what do you think?

**Review by niteshseram — DISMISSED** [review]
Looks good to me. Yes, you can make the demo in separate PR.  But we have to wait for this PR to merge, until then, we can start working on creating a demo by creating a branch from its current branch of yours.

**Comment by atapas** [comment]
> Looks good to me. Yes, you can make the demo in separate PR.  But we have to wait for this PR to merge, until then, we can start working on creating a demo by creating a branch from its current branch of yours.

Sounds like a plan. Go ahead. So rest of it will b in one new branch?

**Comment by niteshseram** [comment]
> > Looks good to me. Yes, you can make the demo in separate PR.  But we have to wait for this PR to merge, until then, we can start working on creating a demo by creating a branch from its current branch of yours.
> 
> Sounds like a plan. Go ahead. So rest of it will b in one new branch?

I was thinking to merge this PR to a seperate branch until all the demos PR are merged. Because if this PR is merged in master, the demos will not be available until the PRs for all the demos are merged.

**Comment by atapas** [comment]
> > > Looks good to me. Yes, you can make the demo in separate PR.  But we have to wait for this PR to merge, until then, we can start working on creating a demo by creating a branch from its current branch of yours.
> > 
> > Sounds like a plan. Go ahead. So rest of it will b in one new branch?
> 
> I was thinking to merge this PR to a seperate branch until all the demos PR are merged. Because if this PR is merged in master, the demos will not be available until the PRs for all the demos are merged.

Got it. We can do that...my question was more to understand, how soon the rest of it will be available.

**Comment by niteshseram** [comment]
> > > > Looks good to me. Yes, you can make the demo in separate PR.  But we have to wait for this PR to merge, until then, we can start working on creating a demo by creating a branch from its current branch of yours.
> > > 
> > > 
> > > Sounds like a plan. Go ahead. So rest of it will b in one new branch?
> > 
> > 
> > I was thinking to merge this PR to a seperate branch until all the demos PR are merged. Because if this PR is merged in master, the demos will not be available until the PRs for all the demos are merged.
> 
> Got it. We can do that...my question was more to understand, how soon the rest of it will be available.

About that @mverissimo can confirm it.

**Comment by mverissimo** [comment]
> > > > > Looks good to me. Yes, you can make the demo in separate PR.  But we have to wait for this PR to merge, until then, we can start working on creating a demo by creating a branch from its current branch of yours.
> > > > 
> > > > 
> > > > Sounds like a plan. Go ahead. So rest of it will b in one new branch?
> > > 
> > > 
> > > I was thinking to merge this PR to a seperate branch until all the demos PR are merged. Because if this PR is merged in master, the demos will not be available until the PRs for all the demos are merged.
> > 
> > 
> > Got it. We can do that...my question was more to understand, how soon the rest of it will be available.
> 
> About that @mverissimo can confirm it.

Yep, I will start a new branch from this, but before I need that this is reviewed before, to prevent some breaking change.

So after all work is done, we need to follow these steps:
- Merge this branch on master
- After this, all other branches created from this will have their base(this) automatically changed to master
- On end only need merge

**Comment by niteshseram** [comment]
> > > > > > Looks good to me. Yes, you can make the demo in separate PR.  But we have to wait for this PR to merge, until then, we can start working on creating a demo by creating a branch from its current branch of yours.
> > > > > 
> > > > > 
> > > > > Sounds like a plan. Go ahead. So rest of it will b in one new branch?
> > > > 
> > > > 
> > > > I was thinking to merge this PR to a seperate branch until all the demos PR are merged. Because if this PR is merged in master, the demos will not be available until the PRs for all the demos are merged.
> > > 
> > > 
> > > Got it. We can do that...my question was more to understand, how soon the rest of it will be available.
> > 
> > 
> > About that @mverissimo can confirm it.
> 
> Yep, I will start a new branch from this, but before I need that this is reviewed before, to prevent some breaking change.
> 
> So after all work is done, we need to follow these steps:
> 
> * Merge this branch on master
> * After this, all other branches created from this will have their base(this) automatically changed to master
> * On end only need merge

Just a small one more change @mverissimo. Yesterday, I told you to make the preview align from left. Just make the align from left in big screen. For mobile, make it align to center. After that, you can create a a branch from this current branch and start for others demo.

**Review by niteshseram — COMMENTED** [review]
I see there is some issue with the image capture API. The image is not shown on the screen. Is the migration of API completed? @mverissimo

**Comment by mverissimo** [comment]
> I see there is some issue with the image capture API. The image is not shown on the screen. Is the migration of API completed? @mverissimo

I'm investigating, but don't maybe you can help me with this?

**Comment by niteshseram** [comment]
> > I see there is some issue with the image capture API. The image is not shown on the screen. Is the migration of API completed? @mverissimo
> 
> I'm investigating, but don't maybe you can help me with this?

I will have a look at it. Others are done?

**Comment by mverissimo** [comment]
> > > I see there is some issue with the image capture API. The image is not shown on the screen. Is the migration of API completed? @mverissimo
> > 
> > 
> > I'm investigating, but don't maybe you can help me with this?
> 
> I will have a look at it. Others are done?

Yep, all done!

**Comment by atapas** [comment]
> > > > I see there is some issue with the image capture API. The image is not shown on the screen. Is the migration of API completed? @mverissimo
> > > 
> > > 
> > > I'm investigating, but don't maybe you can help me with this?
> > 
> > 
> > I will have a look at it. Others are done?
> 
> Yep, all done!

@niteshseram when u can please do a full test, review and all goes well, merge.

Thanks!

**Comment by atapas** [comment]
@mverissimo @niteshseram What's the plan for this to go to master?

**Comment by niteshseram** [comment]
> @mverissimo @niteshseram What's the plan for this to go to master?

I am going through demo from the develop branch and checking if there is any issue. Once verified we can merge to master. But I am getting  slow due to my tight schedule.

**Comment by atapas** [comment]
> > @mverissimo @niteshseram What's the plan for this to go to master?
> 
> I am going through demo from the develop branch and checking if there is any issue. Once verified we can merge to master. But I am getting  slow due to my tight schedule. 

Good plan.

**Comment by atapas** [comment]
I'll be testing the changes from tomorrow on the develop branch. Let's plan a master update by this weekend.

**Pull request merged**
