### PR TITLE
feat: create webRTC api demo

### PR DESCRIPTION
**Pull request by raveenita**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Implements WebRTC API demo with the `getDisplayMedia` and `getUserMedia` examples

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

I  didn't write any tests because I don't saw any test at all, but I can do it if was needed!

# Checklist:

- [x] My code follows the [style guidelines](https://github.com/atapas/webapis-playground/blob/master/HOW-TO-ADD-DEMO.md) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by raveenita** [comment]
I didn't get why the deployment has failed. If you could explain if I did something wrong, I can fix it!

**Comment by raveenita** [comment]
@atapas In the issue https://github.com/atapas/webapis-playground/issues/164 you comment that WebRTC is able to exchange arbitrary data between browsers without requiring an intermediary. I would love to implement this later too, but know I decided to implement only screensharing and video and audio recording

**Comment by atapas** [comment]
> I didn't get why the deployment has failed. If you could explain if I did something wrong, I can fix it!

The build failed due to the Node.js dependency. I have fixed that on vercel.

**Comment by atapas** [comment]
> 

I am reviewing the changes @raveenita

**Review by atapas — COMMENTED** [review]
@raveenita Can we give an option for Mp4 download too?

**Comment by raveenita** [comment]
@atapas of course! I'll work on this

**Comment by raveenita** [comment]
It's done, @atapas =)

**Comment by atapas** [comment]
@raveenita one last thing..

On mobile the button alignments can be improved. Will you please take care of that?

image

**Comment by raveenita** [comment]
@atapas done!
image

**Comment by raveenita** [comment]
@atapas ? ='(

**Review by atapas — APPROVED** [review]
@raveenita My looooong vacation delayed it.. sorry. Now done.

**Pull request merged**
