### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by atapas**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [ ] My code follows the [style guidelines](https://github.com/atapas/webapis-playground/blob/master/HOW-TO-ADD-DEMO.md) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by atapas** [comment]
Started Testing this PR

@mverissimo @niteshseram @max-programming 

I shall post my update here.

**Comment by atapas** [comment]
## Test Results

1. Listing of all demos ✅
2. Search of demos ✅
3. Logo ✅
4. GitHub Icon ✅
5. Twitter Icon ✅
6. FileSystem Demo ✅
7. Full Screen ✅
8. Clipboard ✅
9. Broadcast ✅
10. Network ✅
11. Resize Observer ✅
12. Web Payment API ✅
13. Vibration 
14. Battery ✅
15. DnD ✅
16. Image Capture ✅
17. Web Share ✅
> The demo works. However, the description is having a character that doesn't render well. Can be taken as a separate issue. Hence passing it.
image

18. Geolocation ✅
19. Pic in Pic ✅
20. Screen Capture ✅
21. Web Speech ✅ It is not working as expected. Basic things are working. But behaving in the same ways as it is in master. So not stopping this merge.
22. CSS font loading ✅

Tested on both Desktop and Mobile.

**Comment by atapas** [comment]
@niteshseram @mverissimo 

I have posted my test results. Looks good to merge. Could you please give my update a glance and approve the PR to merge. It will enable others to start contributing on the infrastructure changes.

> Please note, I have not checked any possible Readme changes. Please confirm all the related readme changes are taken care to suites all the changes in the PR. Once you approve and confirm, I shall merge.

**Comment by atapas** [comment]
> @niteshseram @mverissimo 
> 
> I have posted my test results. Looks good to merge. Could you please give my update a glance and approve the PR to merge. It will enable others to start contributing on the infrastructure changes.
> 
> > Please note, I have not checked any possible Readme changes. Please confirm all the related readme changes are taken care to suites all the changes in the PR. Once you approve and confirm, I shall merge.

A reminder to review and approve this PR.

**Comment by atapas** [comment]
@mverissimo @niteshseram did you get a chance to look into it? Can I merge?

Kindly confirm the readme part for creating demos. Rest I have checked already.

**Comment by mverissimo** [comment]
> @mverissimo @niteshseram did you get a chance to look into it? Can I merge?
> 
> Kindly confirm the readme part for creating demos. Rest I have checked already.

I think is good

**Comment by atapas** [comment]
Merged. Thanks, @mverissimo. It was a significant refactoring and change. Great job. Let's discuss what we want to consider to do next!

**Pull request merged**
