### PR TITLE
Demo 37 push

### PR DESCRIPTION
**Pull request by jesse-moore**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # 37

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [X] My code follows the [style guidelines](https://github.com/atapas/webapis-playground/blob/master/HOW-TO-ADD-DEMO.md) of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by atapas** [comment]
> You will need to goto https://web-push-codelab.glitch.me/ and generate a public and private key for the Push API and set these corresponding environment keys in Vercel.
> PUSH_API_PRIVATE_KEY
> NEXT_PUBLIC_PUSH_API_PUBLIC_KEY

Great I will add these in the vercel deployment env config.

Please except some delays as I'm on vacation. Btw... Who owns that glitch server? Is that something we can create for our project and maintain? I mean, if tomorrow the server is down or the keys doesn't not work, etc.

In the mean time, @niteshseram could you plz do a code review?

**Comment by jesse-moore** [comment]
> Great I will add these in the vercel deployment env config.
> 
> Please except some delays as I'm on vacation. Btw... Who owns that glitch server? Is that something we can create for our project and maintain? I mean, if tomorrow the server is down or the keys doesn't not work, etc.
> 
> In the mean time, @niteshseram could you plz do a code review?

The glitch.me site was referenced in a Google tutorial on Push Notifications [here](https://developers.google.com/web/fundamentals/codelabs/push-notifications#get_application_server_keys). I can make a script command in package.json to generate the keys instead. So instead of going to the external site you could just put npm run genkeys in the command line for example and it would output the keys you need.

**Comment by jesse-moore** [comment]
I added a script so the .env.local file and the required Push API keys can be generated locally.

**Review by niteshseram — COMMENTED** [review]
Code looks good to me. Havn't got time to try this out in my local machine. Will try to do tomorrow.

**Comment by niteshseram** [comment]
@jesse-moore It doesn't seem to be working when I ran in my local machine. Is it working on your end?

**Comment by jesse-moore** [comment]
> @jesse-moore It doesn't seem to be working when I ran in my local machine. Is it working on your end?

Are you getting any errors? I added another library that needs to be installed and an extra step to initialize the API keys in the .env.local file. 
```npm run gen-keys``` will generate a .env.local file and setup the keys for you.

**Comment by niteshseram** [comment]
> > @jesse-moore It doesn't seem to be working when I ran in my local machine. Is it working on your end?
> 
> Are you getting any errors? I added another library that needs to be installed and an extra step to initialize the API keys in the .env.local file. `npm run gen-keys` will generate a .env.local file and setup the keys for you.

When I click on send notification, nothing is happening. I have set up the env variables by running the `npm run gen-keys`

**Comment by atapas** [comment]
@jesse-moore We made a few infrastructural changes. Could you please update the branch with the latest code?

Also, could you please respond to @niteshseram's question above? Looking forward to getting this demo in asap.

**Pull request closed without merging**
