### PR TITLE
👌 IMPROVE: Replace img with Image from Nextjs

### PR DESCRIPTION
**Pull request by rehan-sattar**
# Description

This pr contains:
- Feature completion of #56 
- Replacement of `img` tag with `Image` tag from nextjs. 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the [style guidelines](https://github.com/atapas/webapis-playground/blob/master/HOW-TO-ADD-DEMO.md) of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Review by atapas — CHANGES_REQUESTED** [review]
The full screen image is broken

image

**Comment by rehan-sattar** [comment]
@atapas  Thanks for informing. The problem is that the `Image` adds some extra divs to the dom internally and the logic behind the full-screen image is hardcoded with picking up the image. 

image

I have tried to fix it and it's working but at the same time, it's too much to do for a small thing and increasing complexity. I recommend we can use `img` of html here and can go with the current flow. 

For better understanding please refer to this issue: https://github.com/vercel/next.js/discussions/18312

**Comment by atapas** [comment]
> @atapas Thanks for informing. The problem is that the `Image` adds some extra divs to the dom internally and the logic behind the full-screen image is hardcoded with picking up the image.
> 
> image
> 
> I have tried to fix it and it's working but at the same time, it's too much to do for a small thing and increasing complexity. I recommend we can use `img` of html here and can go with the current flow.
> 
> For better understanding please refer to this issue: [vercel/next.js#18312](https://github.com/vercel/next.js/discussions/18312)

Right, as I was telling you about the challenge in the beginning.. I guess this is the one I faced too... I am ok with living with this one img tag here.

**Comment by atapas** [comment]
@rehan-sattar Shall I close this PR and issue as well?

**Comment by rehan-sattar** [comment]
Yes, we should go with the `img` tag as the application is not using images that much. 

Good to go! :rocket:

**Review by atapas — COMMENTED** [review]
Closing the PR not required

**Comment by niteshseram** [comment]
> Closing the PR not required

@atapas  We should have merged at least for the creator image since it is working.

**Comment by atapas** [comment]
> > Closing the PR not required
> 
> @atapas We should have merged at least for the creator image since it is working.

Yeah I was trying to confirm that before closing. Ok lets do that ina future PR.

**Comment by niteshseram** [comment]
> > > Closing the PR not required
> > 
> > 
> > @atapas We should have merged at least for the creator image since it is working.
> 
> Yeah I was trying to confirm that before closing. Ok lets do that ina future PR.

Yes, we should use next/image wherever possible since it does a lot of things related to performance and optimization behind the scene

**Pull request closed without merging**
