### PR TITLE
refactor(ui): add a new design

### PR DESCRIPTION
**Pull request by mverissimo**
# Description

This proposal introduces a new interface design using the [chakra-ui](https://chakra-ui.com/), that provides some enhancements:
- Better visual ui
- Dark mode
- A lot of components
- Test outside the box
- Flexible ui
- And more

## Other changes

- Typescript
This was totally optioned, the project is recent and we can write the types gradually into the project, I think this help us do a better code along the time.

- Folder structure
The folder _core_ was removed, and the components were moved to the root.

- Componentes naming
Some components were renamed to be more _generic_, this helps us understand the characteristics more easily, the idea is to move some components to the scope of the page, like the `Demo` renamed to `Card`.

- API
The emoji on the title was moved into a new item, to keep the SEO more accurate and a better UI management.

- Design
The `Card` was redesigned, to be cleaner, and **enforce** the user _access to the content_.
And was added `dark mode support.

## NOTE
I did the redesign only on `Homepage`, if this PR is accepted, I will happy to continue working on this.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested on desktop, tablet, and mobile devices.

# Checklist:

- [x] My code follows the [style guidelines](https://github.com/atapas/webapis-playground/blob/master/HOW-TO-ADD-DEMO.md) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by atapas** [comment]
@mverissimo Thanks for putting it together. I haven't used `chakra` before but heard about it. Do you see it having any issues with TailwindCSS together? We will support themes and other customizations in the future. So I want to confirm, we have researched any impact of an incoming library with the existing ones.

Btw.. the UI improvements so far look fab!

**Comment by mverissimo** [comment]
Hello @atapas, I really like to use `TailwindCSS` too, but he works more efficiently with landing pages because we can code a customized layout fast. When starts talk about systems, I think he does not scale well, we need to implement events, accessibility, new components and think about the maintainability along the time, how any system. So I chose `chakra` because we have a lot of `components` tested, accessible, etc, and we can create custom themes with him.

**Comment by niteshseram** [comment]
I won't recommend using chakra ui from my personal experience. Chakra ui is definitely great but for large project. But in small project, it cost us performance. Using tailwind css gives us a great load time.

**Comment by atapas** [comment]
> Hello @atapas, I really like to use `TailwindCSS` too, but he works more efficiently with landing pages because we can code a customized layout fast. When starts talk about systems, I think he does not scale well, we need to implement events, accessibility, new components and think about the maintainability along the time, how any system. So I chose `chakra` because we have a lot of `components` tested, accessible, etc, and we can create custom themes with him. 

Let me tell you, I loved the UI transformation a lot. It look very silky and the theme switcher works well already for the landing page. The demo pages have more work to do but I understand it is work in progress.

I'm concerned of having both tailwindcss and chakra both for a small project like this. We should go for one of them I feel. What's your thought of continuing the UI look and feel change using tailwind? Would you be comfortable taking it up? I really liked your work and appreciate it so far.

**Comment by niteshseram** [comment]
My take on this is that I would highly recommend to continue with tailwind. No doubt chakra ui is great and appreciate your effort for that beautiful ui. But from my experience, I think tailwind css has great site loading time and performance with small project.

**Comment by mverissimo** [comment]
> > Hello @atapas, I really like to use `TailwindCSS` too, but he works more efficiently with landing pages because we can code a customized layout fast. When starts talk about systems, I think he does not scale well, we need to implement events, accessibility, new components and think about the maintainability along the time, how any system. So I chose `chakra` because we have a lot of `components` tested, accessible, etc, and we can create custom themes with him.
> 
> Let me tell you, I loved the UI transformation a lot. It look very silky and the theme switcher works well already for the landing page. The demo pages have more work to do but I understand it is work in progress.
> 
> I'm concerned of having both tailwindcss and chakra both for a small project like this. We should go for one of them I feel. What's your thought of continuing the UI look and feel change using tailwind? Would you be comfortable taking it up? I really liked your work and appreciate it so far.

I appreciate that you like the new design 😄 🚀 , maybe we can use both `Tailwind` on the landing page and `Chakra` on system general, what do you think? Personally prefer to keep using them because require less work, otherwise, we need to create a small set of components like, `Button`, `Input`, `Typography`, to reduce rewrite some styles with `Tailwind`, and this prevents that new contributors create new `components` unnecessary.

About the `Demo page`, I pretend to work on them soon, just waiting for the response on `issue` and our decision about the library that we use 😃

**Comment by mverissimo** [comment]
> My take on this is that I would highly recommend to continue with tailwind. No doubt chakra ui is great and appreciate your effort for that beautiful ui. But from my experience, I think tailwind css has great site loading time and performance with small project.

I agree with you, this is a small project maybe we don't need the `Chakra`, but I think that this project will grow with time, many other guys will send some demo, and with this, more and more components, and about the performance I can't see a real impact, we can perform this with next(SSG, SSR), and the `demos` are simple in general.

**Pull request closed without merging**
