### PR TITLE
refactor(header): new design

### LINKED ISSUE #51: 💡 [Feature]: UI update for more contemporary look
**Is your feature request related to a problem? Please describe.**
This is a great application without a single doubt. A more contemporary aesthetic will be icing on the cake.

**Describe the solution you'd like**
A modern UI transformation

**Describe alternatives you've considered**
NA

**Additional context**
NA

### PR DESCRIPTION
**Pull request by mverissimo**
# Description

This PRS includes a new header design, the `dark mode` it will be added after all layout changes.

NOTE:
_Do we have a `new logo` design to add? @atapas_ 

## Others changes

- Typescript
This was totally optioned, the project is recent and we can write the types gradually into the project, I think this help us do a better code along the time.

- Tailwind
Was enabled the `jit` mode, and imported the `base` styles.

Fixes #51 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [x] My code follows the [style guidelines](https://github.com/atapas/webapis-playground/blob/master/HOW-TO-ADD-DEMO.md) of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by mverissimo** [comment]
Hello, @niteshseram @atapas any update about this? I would like to continue doing this.

**Comment by mverissimo** [comment]
> Should be good to go after these changes +1

Good, done!

**Comment by atapas** [comment]
> > Should be good to go after these changes +1
> 
> Good, done!

Please make sure to use the updated logo.

**Comment by mverissimo** [comment]
> > > Should be good to go after these changes +1
> > 
> > 
> > Good, done!
> 
> Please make sure to use the updated logo.

I think it's right

**Comment by niteshseram** [comment]
> > > > Should be good to go after these changes +1
> > > 
> > > 
> > > Good, done!
> > 
> > 
> > Please make sure to use the updated logo.
> 
> I think it's right

He might be referring to this [logo](https://github.com/atapas/webapis-playground/blob/master/public/assets/svg/logoDark.svg)

**Comment by mverissimo** [comment]
> > > > > Should be good to go after these changes +1
> > > > 
> > > > 
> > > > Good, done!
> > > 
> > > 
> > > Please make sure to use the updated logo.
> > 
> > 
> > I think it's right
> 
> He might be referring to this [logo](https://github.com/atapas/webapis-playground/blob/master/public/assets/svg/logoDark.svg)

Ok, I replaced the logo! Tks

**Comment by atapas** [comment]
@mverissimo 

Thanks a lot for taking the issue and making the app better. Please feel free to pick up more, contribute more. I wish you a great #Hactoberfest ahead. You will be added to the contribution list right after we merge this PR. Don't forget to share about your contribution publicly and provide your support with a star ⭐.

Great work 🔥 !!!!

**Comment by atapas** [comment]
@all-contributors please add @mverissimo  for Code

**Pull request merged**
