### PR TITLE
fix(demos): fix few demos ui breaking on mobile

### LINKED ISSUE #53: 🐛 [Bug]: A few demo interface breaks in the mobile resolution
**Describe the bug**
These demos are breaking in a smaller resolution.

- https://webapis-playground.vercel.app/demos/picture-in-picture
- https://webapis-playground.vercel.app/demos/filesystem-api
- https://webapis-playground.vercel.app/demos/broadcast-channel
- https://webapis-playground.vercel.app/demos/vibration
- https://webapis-playground.vercel.app/demos/image-capture
Kindly check all other demos also

**Expected behavior**
The UI shouldn't break in responsive mode.

**Screenshots**
image

image

image

image

image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by AhsanAyaz**
# Description

Fixed the UI issues happening on the mobile for a few demos
removed some react styles and used pure tailwind CSS instead
I feel great
CodeWithAhsan community is awesome
You are also awesome to create this repo (project)
Hacktobefest is awesome
I'm hungry

Fixes #53

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the [style guidelines](https://github.com/atapas/webapis-playground/blob/master/HOW-TO-ADD-DEMO.md) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by atapas — CHANGES_REQUESTED** [review]
Hey @AhsanAyaz could you please pull the latest of master and update your branch? I would like to test it on the latest code and merge it. Thanks a lot.

**Comment by AhsanAyaz** [comment]
@atapas. Updated w.r.t latest `master`. Let's see!

**Review by atapas — APPROVED** [review]
@AhsanAyaz Changes are looking good. Approving

**Comment by atapas** [comment]
@AhsanAyaz 

Thanks a lot for taking the issue and making the app better. Please feel free to pick up more, contribute more. I wish you a great #Hactoberfest ahead. You will be added to the contribution list right after we merge this PR. Don't forget to share about your contribution publicly and provide your support with a star ⭐.

Great work 🔥 !!!!

**Comment by atapas** [comment]
@all-contributors please add @AhsanAyaz  for Code

**Pull request merged**
