### PR TITLE
Added a Alphabetial Sort Function to getAllDemos()

### PR DESCRIPTION
**Pull request by brandon-1999**
# Description

I Added Alphabetical sorting to the getAllDemos() in order to make the user experience more intuitive.

Fixes # (issue)

## Type of change
 - Changed ordering of demo display to sort alphabetically
Please delete options that are not relevant.

- [x ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
-Reloaded the project and everything works fine.

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [x] My code follows the [style guidelines](https://github.com/atapas/webapis-playground/blob/master/HOW-TO-ADD-DEMO.md) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by atapas** [comment]
Hey @brandon-1999 Could you please let me know the associated issue? Also please send a screenshot of the expected behavior.

**Comment by brandon-1999** [comment]
Absolutely fine. It wasn't related to an issue . Mb on that but yeah will for sure do so in the morning :)

**Comment by atapas** [comment]
> Absolutely fine. It wasn't related to an issue . Mb on that but yeah will for sure do so in the morning :)

Could you please add an issue and link to this PR so that we know what to test from the UI?

**Comment by brandon-1999** [comment]
Yeah no problem. ill raise a new issue too

**Comment by brandon-1999** [comment]
Screenshot of expected behaviour: 
image

Associated issue:

https://github.com/atapas/webapis-playground/issues/69

**Comment by brandon-1999** [comment]
I have found a bug that im going to have to fix before this can be commited. in regards to the payment request api and the fact the tile expands if given the offical name. so ill rewrite the sort function to go off titles in stead of id. that way everything will be consistant

**Comment by atapas** [comment]
@brandon-1999 why is this PR closed?

**Comment by brandon-1999** [comment]
I closed it because the web payment API tile has a different title to the ID. So it wasn't placed correctly. Upon changing the title to match the Id, the tile expanded to misallign with the other tiles. So that's a bit of an issue. Figured I would put up an issue about the tile expanding but then I realised there is a guy working on the UI currently to give it a more contemporary look. So I'd have to wait for that to be pushed before I could fix that issue. I considered ordering based on titles instead. Which is what I am going to do. Then, put in a new pull request when I have finished.

Sorry for the mess. This is the first time I have ever worked on a project :(

**Comment by atapas** [comment]
> I closed it because the web payment API tile has a different title to the ID. So it wasn't placed correctly. Upon changing the title to match the Id, the tile expanded to misallign with the other tiles. So that's a bit of an issue. Figured I would put up an issue about the tile expanding but then I realised there is a guy working on the UI currently to give it a more contemporary look. So I'd have to wait for that to be pushed before I could fix that issue. I considered ordering based on titles instead. Which is what I am going to do. Then, put in a new pull request when I have finished.
> 
> Sorry for the mess. This is the first time I have ever worked on a project :(

No worries at all. It's quite normal 😀

**Pull request closed without merging**
