### PR TITLE
Refactor/demo file clipboard

### PR DESCRIPTION
**Pull request by mverissimo**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [ ] My code follows the [style guidelines](https://github.com/atapas/webapis-playground/blob/master/HOW-TO-ADD-DEMO.md) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by mverissimo** [comment]
Hey @niteshseram Can you help me? I cannot change the `base branch` to -> `mverissimo:refactor/demo-page` have a way to do this?

**Comment by niteshseram** [comment]
> Hey @niteshseram Can you help me? I cannot change the `base branch` to -> `mverissimo:refactor/demo-page` have a way to do this?

No, it is not possible to do like that. It's okay. I will change the branch accordingly.

**Comment by mverissimo** [comment]
> > Hey @niteshseram Can you help me? I cannot change the `base branch` to -> `mverissimo:refactor/demo-page` have a way to do this?
> 
> 
> 
> No, it is not possible to do like that. It's okay. I will change the branch accordingly.

Huum, so I think this be done in a single PR, it's okay for you?

**Comment by atapas** [comment]
> > > Hey @niteshseram Can you help me? I cannot change the `base branch` to -> `mverissimo:refactor/demo-page` have a way to do this?
> > 
> > 
> > No, it is not possible to do like that. It's okay. I will change the branch accordingly.
> 
> Huum, so I think this be done in a single PR, it's okay for you?

Yeah, should be fine with me if that makes it easier.

**Comment by mverissimo** [comment]
> > > > Hey @niteshseram Can you help me? I cannot change the `base branch` to -> `mverissimo:refactor/demo-page` have a way to do this?
> > > 
> > > 
> > > No, it is not possible to do like that. It's okay. I will change the branch accordingly.
> > 
> > 
> > Huum, so I think this be done in a single PR, it's okay for you?
> 
> Yeah, should be fine with me if that makes it easier.

The only point is many files to your review but doesn't have another way.

**Comment by atapas** [comment]
> > > > > Hey @niteshseram Can you help me? I cannot change the `base branch` to -> `mverissimo:refactor/demo-page` have a way to do this?
> > > > 
> > > > 
> > > > No, it is not possible to do like that. It's okay. I will change the branch accordingly.
> > > 
> > > 
> > > Huum, so I think this be done in a single PR, it's okay for you?
> > 
> > Yeah, should be fine with me if that makes it easier.
> 
> The only point is many files to your review but doesn't have another way.

We can make logical commits and review per commits. If done as planned, it is unlikely, one commit for a demo will impact another demo related files. So should be ok, I believe.

**Pull request closed without merging**
