### PR TITLE
added new web api: url api

### PR DESCRIPTION
**Pull request by williamssam**
# Description
The URL API is a component of the URL standard, which defines what constitutes a valid [Uniform Resource Locator](https://developer.mozilla.org/en-US/docs/Glossary/URL) and the API that accesses and manipulates URLs.

Fixes # 155

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [ x] My code follows the [style guidelines](https://github.com/atapas/webapis-playground/blob/master/HOW-TO-ADD-DEMO.md) of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by atapas** [comment]
@williamssam I tried the parse URl but didn't find it working.. Possible to screen record and post what is expected?

**Comment by williamssam** [comment]
Oops, I just noticed the bug. Sorry about that. I will push the fix now

**Review by atapas — APPROVED** [review]
Great work @williamssam. Looks good to me to accept.

**Comment by atapas** [comment]
@all-contributors please add @williamssam for Code

**Pull request merged**
