### PR TITLE
refactor(card): new design

### PR DESCRIPTION
**Pull request by mverissimo**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

This PRS includes a new `Card Demo` design.

## Changes

- Button
  Was added a reusable Button

- Tailwind
  Was added the [tailwind-line-clamp](https://github.com/tailwindlabs/tailwindcss-line-clamp)

- Demo API
  The `emoji` was extracted into a new `object` to easy reuse on design and improve SEO.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [x] My code follows the [style guidelines](https://github.com/atapas/webapis-playground/blob/master/HOW-TO-ADD-DEMO.md) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by mverissimo** [comment]
@atapas @niteshseram ready for review!

Have an Issue to link this PR?

**Comment by atapas** [comment]
The changes are looking so very cool. Thanks a lot @mverissimo for making it. Thanks @niteshseram for the reviews.

I have found a couple of tiny regressions.. Could you plz fix @mverissimo . I shall merge right after that...

## Full Screen API

The button is merged with Rock!

image


## Image capture demo... The output images should be positioned correctly.

image

## Geolocation Demo

This link doesn't look like a link.

image

**Comment by niteshseram** [comment]
> The changes are looking so very cool. Thanks a lot @mverissimo for making it. Thanks @niteshseram for the reviews.
> 
> I have found a couple of tiny regressions.. Could you plz fix @mverissimo . I shall merge right after that...
> 
> ## Full Screen API
> The button is merged with Rock!
> 
> image
> 
> ## Image capture demo... The output images should be positioned correctly.
> image
> 
> ## Geolocation Demo
> This link doesn't look like a link.
> 
> image

He is just designing the look of the card on the homepage I guess in this PR. Maybe what is inside the card can be fixed in another PR.

**Comment by niteshseram** [comment]
Fixing the what inside the card will also come with fixing the button, font, alignment and all those things

**Pull request merged**
